# Generated by Django 5.1.2 on 2024-11-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
