# Generated by Django 5.1.2 on 2024-11-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bids_create_at_bids_updated_at_comments_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
