# Generated by Django 5.1.2 on 2024-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_products_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img_url',
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, default='unknown.png', upload_to=''),
        ),
    ]
