# Generated by Django 5.1.2 on 2024-11-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_products_img_url_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, default='unknown.png', upload_to='product_image/'),
        ),
    ]
